### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by saddang** [adrielyeung/automated-file-download#1]
Hey!

It would be easier to add chromedriver via the library without needing to define:
```
import chromedriver_autoinstaller

# This checks if the current version of chromedriver exists
# and if it doesn't exist, downloads it automatically,
# then adds chromedriver to path
chromedriver_autoinstaller.install()
```

**Comment by adrielyeung** [comment]
Hey @saddang, thanks for your interest in this project. Your changes look great. I am testing it but have trouble installing ```chromedriver_autoinstaller``` package.

Could you let me know how to install ```chromedriver_autoinstaller``` using Anaconda? I am using conda 4.10.1 . Thanks a lot.

**Comment by saddang** [comment]
Hi @adrielyeung! I think you can only install via terminal.
![image](https://user-images.githubusercontent.com/84881387/120724566-17ebaf80-c4a2-11eb-95b5-f0e5b3415151.png)

In terminal, run this:
`pip install chromedriver-autoinstaller`
![image](https://user-images.githubusercontent.com/84881387/120724586-1fab5400-c4a2-11eb-8880-9484f41f877e.png)

**Comment by adrielyeung** [comment]
Thanks a lot @saddang, I have installed it and your changes are working fine on my computer. Thanks for your suggestion again, and let me know if you have further improvements!
